service: poker
frameworkVersion: "3"
custom:
  dynamodb:
    stages:
      - test
      - dev
    start:
      port: 8001
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true

provider:
  name: aws
  runtime: nodejs16.x
  websocketsApiRouteSelectionExpression: $request.body.route

plugins:
  - serverless-dynamodb-local
  - serverless-plugin-existing-s3
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline
resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: tableId
            AttributeType: S
        KeySchema:
          - AttributeName: tableId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: pokerTable
functions:
  ping:
    handler: src/functions/handler.ping
  websocket:
   handler: src/functions/handler.websocket
   events:
     - websocket:
         route: $connect
     - websocket:
         route: $disconnect
     - websocket:
         route: $default